---
- hosts: rig
  remote_user: loic
  tasks:
    - name: Include AWS crediential variables
      include_vars:
        file: "secrets/aws/credentials.yaml"
    - name: import AWS role
      import_role:
        name: aws
