---
- hosts: all
  become: yes
  tasks:
    - name: set hostname "{{ hostname }}"
      hostname:
        name: "{{ hostname }}"

    - name: Delete root password
      command: passwd -d root

    - name: Disallow password authentication
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        backrefs: yes
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin yes"
        line: "PermitRootLogin no"
        backrefs: yes
      notify: Restart ssh

    - name: disable SELinux
      lineinfile: 
        dest: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"
        backrefs: yes
      notify: reboot 
    
    - name: configure fstab and mount nas disk
      mount: 
        src: UUID="{{ nas_disk_uuid }}"
        path: /mnt/nas #is created if needed
        fstype: ext4
        state: mounted
        passno: 2
        opts: defaults,nofail
    
    - name: upgrade all packages
      yum: name=* state=latest

    - name: install epel-release
      #needed for other packages later
      yum: 
        name : epel-release
        state : latest

    - name: install common packages
      yum: 
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - git
          - htop 
          - yum-utils 
          - unzip
          - curl
          - wget

  handlers:
    - name: Restart ssh
      shell: sleep 3; /etc/init.d/sshd restart
      async: 1
      poll: 0
    - name: reboot 
      reboot: 
