---
- hosts: rig
  remote_user: loic
  become: yes
  vars:
    nextcloud_version: 15.0.0
    nextcloud_path: /var/www/html/nextcloud
    nextcloud_data: /mnt/nas/nextcloud-data
  tasks:

    - name: Install apache (httpd) and php
      import_role: 
        name: httpd

    - name: Include mariadb passwords
      include_vars:
        file: "secrets/mariadb/passwords.yaml"
        name: mariadb

    - name: setup mariadb
      vars: 
        mariadb_datadir: /mnt/nas/mariadb
        mariadb_root_password: "{{ mariadb.mariadb_root_password }}"
        mariadb_databases:
          - name: nextcloud
        mariadb_users:
          - name: nextcloud
            password: "{{ mariadb.mariadb_nextcloud_password }}"
            priv: "nextcloud.*:ALL"
            host: localhost
      import_role:
        name: mariadb

    - name: check if nextcloud is installed
      command: "ls {{ nextcloud_path }}"
      register: nxc
      ignore_errors: True
    
    - name: download nextcloud
      get_url:
        url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
        dest: /tmp
        checksum: "md5:https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip.md5"
      when: nxc.rc > 0 

    - name: install nextcloud
      unarchive:
        src: "/tmp/nextcloud-{{ nextcloud_version }}.zip"
        dest: /var/www/html
        owner: apache
        group: apache
        remote_src: yes
      when: nxc.rc > 0
    
    - name: link data directory to nextcloud
      file:
        src: "{{ nextcloud_data }}"
        path: "{{ nextcloud_path }}/data"
        state: link
        owner: apache
        group: apache
        mode: u=rwx,g=rx
      notify: restart apache

    - name: Authorize traffic in firewall
      firewalld:  
        immediate : yes
        permanent:  yes
        service: "{{ item }}"
        zone: public
        state: enabled
      loop:
        - https
        - http

  
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted


           


       
