---
- hosts: rig
  remote_user: loic
  become: yes
  vars:
    nextcloud_version: 15.0.0
    nextcloud_path: /var/www/html/nextcloud
    nextcloud_data: /mnt/nas/nextcloud-data
  tasks:
    - name : install few dependencies
      yum:
        name : "{{ packages }}"
        state: latest
      vars:
        packages:
          - policycoreutils-python 
          - mlocate
          - bzip2
          - centos-release-scl #for new php version and nextcloud
    
    - name: install apache (httpd)
      yum: name=httpd state=latest
    
    - name: copy httpd config file
      copy:
        src: files/nextcloud/nextcloud.conf
        dest: /etc/httpd/conf.d/nextcloud.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: enable httpd on boot and start it
      systemd:
        name: httpd
        enabled: True
        state: started

    - name: install PHP 7.2 core and modules
      yum: 
        name: "{{ packages }}"
      vars:
        packages:
          - rh-php72
          - rh-php72-php
          - rh-php72-php-gd
          - rh-php72-php-mbstring
          - rh-php72-php-intl
          - rh-php72-php-pecl-apcu
          - rh-php72-php-mysqlnd
          - rh-php72-php-pecl-redis
          - rh-php72-php-opcache
          - rh-php72-php-imagick

    - name: create symbolic links for PHP
      file:
        src: "{{ item.src }}"
        path: "{{ item.dst }}"
        state: link 
      loop:
        #create symbolic link to src file in dst dir
        - {src: /opt/rh/httpd24/root/etc/httpd/conf.d/rh-php72-php.conf,
           dst: /etc/httpd/conf.d/rh-php72-php.conf}
        - {src: /opt/rh/httpd24/root/etc/httpd/conf.modules.d/15-rh-php72-php.conf,
           dst: /etc/httpd/conf.modules.d/15-rh-php72-php.conf}
        - {src: /opt/rh/httpd24/root/etc/httpd/modules/librh-php72-php7.so,
           dst: /etc/httpd/modules/librh-php72-php7.so}
        - {src: /opt/rh/rh-php72/root/bin/php,
           dst: /usr/bin/php}

    - name: Include mariadb passwords
      include_vars:
        file: "secrets/mariadb/passwords.yaml"
        name: mariadb

    - name: setup mariadb
      vars: 
        mariadb_datadir: /mnt/nas/mariadb
        mariadb_root_password: "{{ mariadb.mariadb_root_password }}"
        mariadb_databases:
          - name: nextcloud
        mariadb_users:
          - name: nextcloud
            password: "{{ mariadb.mariadb_nextcloud_password }}"
            priv: "nextcloud.*:ALL"
            host: localhost
      import_role:
        name: mariadb

    - name: check if nextcloud is installed
      command: "ls {{ nextcloud_path }}"
      register: nxc
      ignore_errors: True
    
    - name: download nextcloud
      get_url:
        url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
        dest: /tmp
        checksum: "md5:https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip.md5"
      when: nxc.rc > 0 

    - name: install nextcloud
      unarchive:
        src: "/tmp/nextcloud-{{ nextcloud_version }}.zip"
        dest: /var/www/html
        owner: apache
        group: apache
        remote_src: yes
      when: nxc.rc > 0
    
    - name: link data directory to nextcloud
      file:
        src: "{{ nextcloud_data }}"
        path: "{{ nextcloud_path }}/data"
        state: link
        owner: apache
        group: apache
        mode: u=rwx,g=rx
      notify: restart apache

    - name: Authorize traffic in firewall
      firewalld:  
        immediate : yes
        permanent:  yes
        service: "{{ item }}"
        zone: public
        state: enabled
      loop:
        - https
        - http

  
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted


           


       
