---
- hosts: rig
  remote_user: loic
  tasks:
    - name: Delete root password
      become: yes
      command: passwd -d root


    - name: Disallow password authentication
      become: yes
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        backrefs: yes
      notify: Restart ssh

    - name: Disallow root SSH access
      become: yes
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin yes"
        line: "PermitRootLogin no"
        backrefs: yes
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      shell: sleep 3; /etc/init.d/sshd restart
      async: 1
      poll: 0
