---
- hosts: rig
  remote_user: loic
  vars:
    nas_disk_uuid: "6111e246-08d1-46c2-9ae5-2ebf89c22986"
  tasks:
    - name: Delete root password
      become: yes
      command: passwd -d root

    - name: Disallow password authentication
      become: yes
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        backrefs: yes
      notify: Restart ssh

    - name: Disallow root SSH access
      become: yes
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin yes"
        line: "PermitRootLogin no"
        backrefs: yes
      notify: Restart ssh
    
    - name: configure fstab and mount nas disk
      become: yes
      mount: 
        src: UUID={{ nas_disk_uuid }}
        path: /mnt/nas #is created if needed
        fstype: btrfs 
        state: mounted
        passno: 2
    
        #    - name: upgrade all packages
        #become: yes
        #yum: name=* state=latest

    


  handlers:
    - name: Restart ssh
      shell: sleep 3; /etc/init.d/sshd restart
      async: 1
      poll: 0
