# roles/mariadb/tasks/config.yml
---

- name: create data directory
  file:
    path: "{{ mariadb_datadir }}"
    state: directory 
    owner: mysql
    group: mysql
    mode: u=rwx 

- name: Install mariadb config file
  template:
    src: mariadb.cnf.j2
    dest: /etc/my.cnf.d/mariadb.cnf
  notify: restart mariadb
  tags: mariadb

- name: Ensure service is enabled and started
  service:
    name: mariadb
    state: started
    enabled: true
  tags: mariadb
