---
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "vars/{{ ansible_distribution }}.yaml"
      - "vars/{{ ansible_os_family }}.yaml"
      - vars/default.yaml

- name: install zsh 
  become: pkg_manager_become
  package:
    name: "{{ packages }}"
    state: latest 

- name: make zsh default shell 
  shell: chsh -s $(which zsh)

- name: download and install oh-my-zsh
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: deploy template zshrc 
  template:
    src: templates/zshrc.j2
    dest: ~/.zshrc
