---
- name: install VIM
  become: yes
  package:
    name: vim
    state: latest 
  when: ansible_facts['os_family'] != 'Darwin'

- name: install VIM with homebrew
  package:
    name: vim
    state: latest 
  when: ansible_facts['os_family'] == 'Darwin'

- name: clone Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: deploy template vimrc 
  template:
    src: templates/vimrc.j2
    dest: ~/.vimrc

- name: vundle plugins install
  shell: vim +PluginInstall +qall
    
